# PCA Implementation

## Idea

- There is an encoder and a decoder function.
- Generate optimal eignevectors that minimize the distence between the original points and the reconstruncted points.
- In this implementation we use the singular value decomposition to make this implemntation more generalizable to non-square matrices and higher dimensional matrices.

### Encoder function

$f(x) = Dx$

### Decoder function

$r(x) = g(f(x)) = DD^Tx$

Where $D \in R^{nxl}$ matrix defining the decoding.

### Finding the optimal eigenvectors

- Can be solved using eigendecomposition.
- Optimal $D$ is given by the eigendecomposition of $X^TX$.
- In other implementations of PCA the mean is substracted from $X$ and then eigendecomposition occurs.
- This is equivalent tot he covariance matrix: $cov(X,X) = E[(X-E(X))(X-E(X))]$.
- Matrix $D$ is given by the $l$ eigenvectors corresponing tot he largest eigenvalues.

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data #- np.mean(X,axis=0)
y = iris.target

In [3]:
U, s, V = np.linalg.svd(X, full_matrices=True)

### Eigenvectors of $X^TX$ is V according to the documentation

In [4]:
# eigenvectors are rows of V
V

array([[-0.75116805, -0.37978837, -0.51315094, -0.16787934],
       [ 0.28583096,  0.54488976, -0.70889874, -0.34475845],
       [ 0.49942378, -0.67502499, -0.05471983, -0.54029889],
       [ 0.32345496, -0.32124324, -0.48077482,  0.74902286]])

In [5]:
# singular values
s

array([ 95.95066751,  17.72295328,   3.46929666,   1.87891236])

In [6]:
# number of components
n_components = 3
V = V[:n_components,:]

In [7]:
#encoder function
f_x = np.dot(X,V.T)

In [8]:
#decoder function

g_x = np.dot(f_x,V)

# Results

## Visualize first two rows of reconstructed and original data

In [9]:
print('Reconstructed points: ')
print(g_x[:2,:])
print('\n Original points: ')
print(X[:2,:])

Reconstructed points: 
[[ 5.09935672  3.50063889  1.40095616  0.19851035]
 [ 4.86832748  3.03145595  1.44707719  0.12665612]]

 Original points: 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]]


## Estimate Reconstrunction Error

In [10]:
RE = np.sum(((X-g_x)**2).ravel())
RE

3.5303116664124974

# sklearn implementation

In [11]:
import numpy as np
from sklearn import decomposition
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target

#pca
pca = decomposition.PCA(n_components=3)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [12]:
reconstructed_points = np.dot(pca.transform(X),pca.components_) + np.mean(X,axis=0)

# Results

## Visualize first two rows of reconstructed and original data

In [13]:
print('Reconstructed points: ')
print(reconstructed_points[:2,:])
print('\n Original points: ')
print(X[:2,:])

Reconstructed points: 
[[ 5.09968079  3.50032609  1.40048267  0.19924425]
 [ 4.86840068  3.03228058  1.44778117  0.12518657]]

 Original points: 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]]


## Estimate Reconstrunction Error

In [14]:
RE = np.sum(((X-reconstructed_points)**2).ravel())
RE

3.528771041774291